transcription:
  language: "de"
  nudge_into_punctuation: "Transkription mit Fokus auf Groß- und Kleinschreibung sowie Satzzeichen."
  chunk_step_size: 0.5
  max_timespan: 10
  to_clipboard: true
  to_terminal: true
  terminal_share_progress: true
  separation_confirmed_potential: ""
  terminal_share_eos: false
  terminal_eos: ">><<"
  terminal_eot: "<><>"
recording:
  channels: 1
  rate: 16000
  chunk_size: 16000
processing:
  delay: 0.1
  delays_per_second: 10.0
  stop_timespan_done: 5
  min_timespan_done: 2
  min_dupe_word_count: 2
  min_dupe_between_records_needed: 2
  keep_alive: 60
sound:
  recording_start_active: true
  recording_end_active: true
  processing_end_active: true
  relative_length: 1.0
  relative_volume: 1.0
  relative_speed: 2.0
model:
  name: "turbo"
  device: "cuda"
  compute_type: "float16"
  dir: "./models"
ui:
  enabled: false
